### ISSUE TITLE
OSError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by jdeplato** [automatingosint/osint_public#1]
Great work on this!

Having an issue in which I do not have the technical capacity to figure out.

Installed a clean latest version of Ubuntu:
> DISTRIB_ID=Ubuntu
> DISTRIB_RELEASE=16.04
> NAME="Ubuntu"
> VERSION="16.04.1 LTS (Xenial Xerus)"
> ID=ubuntu
> ID_LIKE=debian
> PRETTY_NAME="Ubuntu 16.04.1 LTS"
> VERSION_ID="16.04"

Went through the [blog post](http://www.automatingosint.com/blog/2016/07/dark-web-osint-with-python-and-onionscan-part-one/) with no problems.

When running it for the first time, encountered the following error:

> OSNAME:~$ python onionrunner.py
> .              .bash_logout  .nano                  onionscan                  .viminfo
> ..             .bashrc       onion_master_list.txt  .profile                   .wget-hsts
> .bash_history  .cache        onionrunner.py         .sudo_as_admin_successful
> [*] Total onions for scanning: 8591
> [*] Running 0 of 8591.
> [*] Onionscanning parabpf4rbfwohre.onion
> Traceback (most recent call last):
>   File "onionrunner.py", line 203, in <module>
>     result = run_onionscan(onion)
>   File "onionrunner.py", line 63, in run_onionscan
>     process = subprocess.Popen(["onionscan","--jsonReport","--simpleReport=false",onion],stdout=subprocess.PIPE,stderr=subprocess.PIPE)
>   File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
>     errread, errwrite)
>   File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
>     raise child_exception
> OSError: [Errno 2] No such file or directory

Tried with ./ in front of the python script with the same result.

Found another post where someone had a similar issue with a different script, they stated:

> I had this error because I was providing a string of arguments to subprocess.call instead of an array arguments. To prevent this, use shlex.split :
> 
> import shlex, subprocess
> command_line = "ls -a"
> args = shlex.split(command_line)
> p = subprocess.Popen(args)

[ Link to that post](http://stackoverflow.com/questions/15725273/python-oserror-errno-2-no-such-file-or-directory)

Added that to the onionrunner script, same results.
Any nugget of info pointing me in some direction to correct this would be great, thanks!

**Comment by jdeplato** [comment]
Figured this out, I had not installed go as the user running the script, but as root. Had to simply install go as the user and everything worked as described.
