### ISSUE TITLE
Errors on bitcoindarkweb.py 

### ISSUE THREAD

**Issue by whatTHEh3ll** [automatingosint/osint_public#5]
I'm getting the following errors when I run the bitcoindarkweb.py script.

I downloaded the osint_public  repo and used my webhose api key. I have python 2.7.10 installed with pyenv.

The errors are as follows.... (The output when I run "python bitcoindarkweb.py --address 19m9yEChBSPuzCzEMmg1dNbPvdLdWA59rS")

[*] Retrieving all transactions from the blockchain for 19m9yEChBSPuzCzEMmg1dNbPvdLdWA59rS
[*] Retrieved 1405 bitcoin transactions.
[*] Identified 6251 unique bitcoin addresses.
[*] Searching 1 of 6251 bitcoin addresses.
Traceback (most recent call last):
  File "bitcoindarkweb.py", line 216, in <module>
    hidden_services = search_webhose(bitcoin_addresses)
  File "bitcoindarkweb.py", line 115, in search_webhose
    result = response.json()
  File "/home/cabox/.pyenv/versions/2.7.10/lib/python2.7/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/home/cabox/.pyenv/versions/2.7.10/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/home/cabox/.pyenv/versions/2.7.10/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/cabox/.pyenv/versions/2.7.10/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by NoahNaugle** [comment]
Having the same issue. Did you solve it?
